### ISSUE TITLE
Compare results from different projects

### ISSUE THREAD

**Issue by arthur-flam** [Samsung/qaboard#8]
**Is your feature request related to a problem? Please describe.**
When working with subprojects, users often want to compare their results versus a different project. For instance, if a subproject is the `v1` of a project, and another is the `v2`, users will want to select `v1` as a reference.

**Describe alternatives you've considered**
So far, users get around the issue by running by either:
- exporting results and comparing with a third-part tool: it's annoying and those 3rd party tools often lack features...
- re-running what they want to compare to as part of their project: it require care  to do right and in the end it's still confusing.

## TODO
- [x] Review the text field that selects a commit: maybe use an icon or a "select" button that hint it's possible to hover and select a different project in a meny (BTW currently we show the available milestones on hover, it's hard to discover. Let's change this too).
- [ ] Offer a select menu with all the related subprojects
- [x] Change `state.selected` so that it's possible to specify a project... Keep in mind it should still be possible to switch new/ref.
- [x] Milestones should save non-default projects, and the non-default project should appear in the milestone selection menu. 
- [x] The `backend/api/export_to_folder.py` has to do the same matching as the web application, so it could require some tweaking... Same goes for `qaboard/optimization.py` when optimizing improvement versus a reference.

**Comment by arthur-flam** [comment]
Done in the last release
